FROM alpine:3.22

RUN apk add --no-cache \
    ca-certificates \
    libgcc

WORKDIR /app

COPY backend/target/x86_64-unknown-linux-musl/release/chhoto-url /app/chhoto-url

RUN chmod +x /app/chhoto-url

EXPOSE 4567

ENTRYPOINT ["/app/chhoto-url"]
